### ISSUE TITLE
java.lang.RuntimeException: Font asset not found special_font.ttf

### ISSUE THREAD

**Issue by RockAriful** [Julow/Unexpected-Keyboard#406]
java.lang.RuntimeException: Unable to create service juloo.keyboard2.Keyboard2: android.view.InflateException: Binary XML file line #2 in juloo.keyboard2:layout/keyboard: Binary XML file line #2 in juloo.keyboard2:layout/keyboard: Error inflating class juloo.keyboard2.Keyboard2View
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4534)
	at android.app.ActivityThread.access$100(ActivityThread.java:306)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: android.view.InflateException: Binary XML file line #2 in juloo.keyboard2:layout/keyboard: Binary XML file line #2 in juloo.keyboard2:layout/keyboard: Error inflating class juloo.keyboard2.Keyboard2View
Caused by: android.view.InflateException: Binary XML file line #2 in juloo.keyboard2:layout/keyboard: Error inflating class juloo.keyboard2.Keyboard2View
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.View.inflate(View.java:27053)
	at juloo.keyboard2.Keyboard2.inflate_view(Keyboard2.java:463)
	at juloo.keyboard2.Keyboard2.onCreate(Keyboard2.java:84)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4522)
	at android.app.ActivityThread.access$100(ActivityThread.java:306)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.RuntimeException: Font asset not found special_font.ttf
	at android.graphics.Typeface.createFromAsset(Typeface.java:976)
	at juloo.keyboard2.Theme.getKeyFont(Theme.java:111)
	at juloo.keyboard2.Theme.<init>(Theme.java:65)
	at juloo.keyboard2.Keyboard2View.<init>(Keyboard2View.java:49)
	... 20 more

**Comment by Julow** [comment]
Thanks for the report. What is your version of Android ?

**Comment by RockAriful** [comment]
This problem is fixed now.

**Comment by RockAriful** [comment]
How help me to implement text suggestion like this 
![Screenshot_2023-07-22-18-58-13-41_da9e875a8d9185d226f0619efbaab124](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/af318942-1b3a-4933-bd01-83eb92bee3c3)


And how to customer this top view woth sone buttons

**Comment by Julow** [comment]
This view is not in the keyboard at the moment so before any customization, we must have a plan for implementing the feature.

Maybe the [SpellCheckerSession](https://developer.android.com/reference/android/view/textservice/SpellCheckerSession?hl=en) class is a good start ?
I have no clue at the moment.

**Comment by RockAriful** [comment]
how to use this SpellCheckerSession?

**Comment by Julow** [comment]
I do not know! You would need to experiment. It might not be the right solution as Hacker's Keyboard don't use it and have their own dictionaries.

**Comment by RockAriful** [comment]
It called CandidateView.

**Comment by RockAriful** [comment]
Please implement it

**Comment by Julow** [comment]
There's an other issue requesting this: https://github.com/Julow/Unexpected-Keyboard/issues/68
