### ISSUE TITLE
Crash after taking screenshot

### ISSUE THREAD

**Issue by islam2hamy** [Julow/Unexpected-Keyboard#736]
FATAL EXCEPTION: main
Process: juloo.keyboard2, PID: 309
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at juloo.keyboard2.g.a(SourceFile:26)
	at juloo.keyboard2.f.onPrimaryClipChanged(Unknown Source:2)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:467)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0(ClipboardManager.java:105)
	at android.content.ClipboardManager$1.$r8$lambda$kJXazWSaZBVUkaNS1pjEccGcb3A(Unknown Source:0)
	at android.content.ClipboardManager$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8727)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by Julow** [comment]
Thanks for the report! Fixed in 4d0598a

**Comment by islam2hamy** [comment]
Thank you
