### ISSUE TITLE
keybord crash

### ISSUE THREAD

**Issue by sb-codz** [Julow/Unexpected-Keyboard#855]
java.lang.NullPointerException: KeyValue payload cannot be null
	at juloo.keyboard2.g0.<init>(SourceFile:1)
	at juloo.keyboard2.g0.<init>(SourceFile:2)
	at juloo.keyboard2.g0.h(SourceFile:1)
	at juloo.keyboard2.l.k(SourceFile:123)
	at juloo.keyboard2.q0.b(SourceFile:1)
	at juloo.keyboard2.l.c(SourceFile:26)
	at juloo.keyboard2.n0.b(SourceFile:1)
	at juloo.keyboard2.o0.j(SourceFile:1)
	at juloo.keyboard2.Keyboard2.a(SourceFile:11)
	at juloo.keyboard2.Keyboard2.onStartInputView(SourceFile:158)
	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2026)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:512)
	at android.view.inputmethod.InputMethod.dispatchStartInputWithToken(InputMethod.java:193)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:539)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:186)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Orzomaxx** [comment]
After update keyboard now crashes in most apps

**Comment by sb-codz** [comment]
Yes after update version 1.30.2

**Comment by Julow** [comment]
Thanks for opening an issue so fast! Should be fixed in e13f586, I'll release soon. You can find a debug build at the end of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/12534202209

**Comment by Julow** [comment]
An update should be available on Google Play now. Do you reproduce the issue ?

**Comment by Spike-from-NH** [comment]
✔ v1.30.3 (from GitHub, not Google Play) lets me call up the keyboard for this input box without crashing; v1.30.2 crashed every time but did let me key into the nav-bar of Fennec.

**Comment by Julow** [comment]
Thank you @sb-codz for opening an issue so fast with a crash logs :) That's extremely helpful.
