### ISSUE TITLE
App crash with some app or field

### ISSUE THREAD

**Issue by ElucGeek** [Julow/Unexpected-Keyboard#859]
The latest update crash with some app or some type of text field in browser.

````
type: crash
osVersion: google/panther/panther:15/AP4A.241205.013/2024120900:user/release-keys
flags: dev options enabled
package: juloo.keyboard2:45, targetSdk 35
process: juloo.keyboard2
processUptime: 190 + 392 ms
installer: dev.imranr.obtainium

java.lang.NullPointerException: KeyValue payload cannot be null
	at juloo.keyboard2.g0.<init>(SourceFile:1)
	at juloo.keyboard2.g0.<init>(SourceFile:2)
	at juloo.keyboard2.g0.h(SourceFile:1)
	at juloo.keyboard2.l.k(SourceFile:123)
	at juloo.keyboard2.q0.b(SourceFile:1)
	at juloo.keyboard2.l.c(SourceFile:26)
	at juloo.keyboard2.n0.b(SourceFile:1)
	at juloo.keyboard2.o0.j(SourceFile:1)
	at juloo.keyboard2.Keyboard2.a(SourceFile:11)
	at juloo.keyboard2.Keyboard2.onStartInputView(SourceFile:158)
	at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:3253)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:3153)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:1050)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:1010)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
`

**Comment by Spike-from-NH** [comment]
Yes, see #855; @Julow has a fix.

**Comment by ElucGeek** [comment]
> Yes, see #855; @Julow has a fix.

OK sorry for double post. I close this one.
